FROM sudachen/jupy2r:latest

#sudachen/jupyter:latest       - Python3, Python2, R 
#sudachen/julia:latest         - jupyter + Julia
#sudachen/jupy2r:latest        - julia + GDrive, DrawIO, ...

USER root
ADD jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py
ADD setup_kernel.py $HOME/.ipython/profile_default/startup/setup_kernel.py
RUN fix-permissions /etc/jupyter/ \
    && fix-permissions ${HOME}/.ipython 
USER $NB_USER

USER root
RUN  echo export PS1=\"\#\ \" >> /root/.bashrc \
     && echo export LS_COLORS=\'ow=01\;36\;40\' >> /root/.bashrc \
     && echo export 'PATH="/opt/conda/bin:$PATH"' >> /root/.bashrc

USER $NB_USER
RUN  echo export PS1=\"\$\ \" >> ${HOME}/.bashrc  \
     && echo export LS_COLORS=\'ow=01\;36\;40\' >> ${HOME}/.bashrc \
     && echo export 'PATH="/opt/conda/bin:$PATH"' >> ${HOME}/.bashrc


