FROM sudachen/jupy3r:latest

#sudachen/jupyter:latest       - Conda Python3, Colab, Google API, PyTorch[CUDA92], OpenCL[MESA] 
#sudachen/jupy3r:latest        - jupyter + PyPy3, Julia, Rust

USER root

RUN usermod -aG video jupyter

ADD jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py
ADD setup_kernel.py $HOME/.ipython/profile_default/startup/setup_kernel.py

RUN fix-permissions /etc/jupyter/ \
    && fix-permissions ${HOME}/.ipython 

RUN  echo export PS1=\"\#\ \" >> /root/.bashrc \
     && echo export LS_COLORS=\'ow=01\;36\;40\' >> /root/.bashrc \
     && echo export 'PATH="/opt/conda/bin:$PATH"' >> /root/.bashrc

USER $NB_USER

RUN  echo export PS1=\"\$\ \" >> ${HOME}/.bashrc  \
     && echo export LS_COLORS=\'ow=01\;36\;40\' >> ${HOME}/.bashrc \
     && echo export 'PATH="/opt/conda/bin:$PATH"' >> ${HOME}/.bashrc

WORKDIR $HOME/work
