version: '3'
services:
  jupyterlab:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ${HOME}/work:/home/jupyter/work
    environment:
      DATABASE_URL: sqlite://
      GITHUB_ACCESS_TOKEN: NONE

#DATABSAE_URL
# redshift/posrgtesql -> postgresql+psycopg2://username:password@host:5439/databasae
# mysql -> mysql+pymysql://username:password@host:3306/database
# inmemory sqlite -> sqlite://

