FROM sudachen/jupyter_r2j:latest

#sudachen/jupyter:latest       - Python3 
#sudachen/jupyter_r2:latest    - Python3, R, Python2
#sudachen/jupyter_r2j:latest   - Python3, R, Python2, Julia
#sudachen/jupyter_r2jx:latest  - Python3, R, Python2, Julia, Scala

USER root
ADD jupyter_notebook_config.py /etc/jupyter/
ADD setup_kernel.py $HOME/.ipython/profile_default/startup/setup_kernel.py
RUN fix-permissions /etc/jupyter/ \
    && fix-permissions ${HOME}/.ipython 

USER $NB_USER

ENV DATABASE_URL=sqlite:// \
    GITHUB_ACCESS_TOKEN=NONE

RUN pip install -U --no-cache-dir git+git://github.com/sudachen/ipython-sql@master 

#USER root
#RUN apt-get update --fix-missing \
#    && apt-get install -qy --no-install-recommends \
#        ip6tables iptables openvpn shadow \
#    && rm -rf /var/lib/apt/lists/* 
#RUN addgroup -S vpn
#ADD openvpn.sh /usr/bin/
#ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/openvpn.sh"]

#RUN pip install -U --no-cache-dir gr 


