#!/bin/bash
echo print\(\"Precompiling julia packages\\n\"\) > /tmp/1.jl
tr -d '\015' < /opt/julia/v0.6/REQUIRE | cut -d " " -f 1 | while read l; 
do if [ -n "$l" ] 
then 
  echo print\(\"using $l\\n\"\) >> /tmp/1.jl;  
  echo using $l >> /tmp/1.jl; \
fi; done  

julia /tmp/1.jl
